version: '3'
services:
  app:
    image: ghcr.io/go-shiori/shiori:v1.5.3
    ports:
      - 8003:8080
    restart: always
    environment:
      - SHIORI_DBMS=postgres
      - SHIORI_PG_HOST=db
      - SHIORI_PG_PORT=5432
      - SHIORI_PG_USER=shiori
      - SHIORI_PG_PASS=shiori
      - SHIORI_PG_NAME=shiori
  db:
    container_name: db
    image: postgres:12.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=shiori
      - POSTGRES_PASSWORD=shiori
      - POSTGRES_DB=shiori
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
