name: Deploy to Server

on:
  push:
    branches:
      - 'master-'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Prod Server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          scp_source: docker-compose.yml
          scp_target: ~/svc/bookmarks/
          before_script: |
            mkdir -p ~/svc/bookmarks/
            cd ~/svc/bookmarks/
            docker-compose down &
          after_script: |
            cd ~/svc/bookmarks/ && docker-compose -p bookmarks_shiori up --build -d
